name: Build QMK Firmware for my GMMK Pro with fix rotary knob
on: [push]
jobs:
  build-malware:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install and configure qmk
        run: |
          python3 -m pip install qmk
          export QMK_HOME='~/qmk_firmware'
          qmk setup --yes
          ls -a

      - name: Build firmware
        run: |
          qmk json2c -o keymap.c gmmk_pro_ansi_layout_mine.json
          ls -lah
          echo -e "\n"  >> keymap.c
          echo -e "bool encoder_update_user(uint8_t index, bool clockwise) {\n    if (clockwise) {\n      tap_code(KC_VOLU);\n    } else {\n      tap_code(KC_VOLD);\n    }\n    return true;\n}" >> keymap.c
          qmk new-keymap -kb gmmk/pro/ansi -km fix_rotary_knob
          rm $QMK_HOME/keyboards/gmmk/pro/ansi/keymaps/fix_rotary_knob/keymap.c
          cp keymap.c $QMK_HOME/keyboards/gmmk/pro/ansi/keymaps/fix_rotary_knob/
          qmk compile -kb gmmk/pro/ansi -km fix_rotary_knob
          ls -lha
          ls -lah $QMK_HOME/keyboards/gmmk/pro/ansi/keymaps/fix_rotary_knob/