name: Release
on:
  workflow_run:
    workflows: ["Build QMK Firmware for my GMMK Pro with fix rotary knob"]
    tags:
      - "v*"
    types: 
      - completed

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:

      - name: Download Artifact from build-firmware job
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build_firmware.yaml
          workflow_conclusion: success
          commit: ${{ github.event.pull_request.head.sha || github.sha }}
          name: gmmk_pro_firmware_with_rotary_knob_fix
          path: ./

      - name: Display structure of downloaded files
        run: ls -lah
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: gmmk_pro_ansi_fix_rotary_knob.bin
